<?xml version="1.0"?>
<!DOCTYPE mame [
<!ELEMENT mame (machine+)>
	<!ATTLIST mame build CDATA #IMPLIED>
	<!ATTLIST mame debug (yes|no) "no">
	<!ATTLIST mame mameconfig CDATA #REQUIRED>
	<!ELEMENT machine (description, year?, manufacturer?, biosset*, rom*, disk*, device_ref*, sample*, chip*, display*, sound?, input?, dipswitch*, configuration*, port*, adjuster*, driver?, feature*, device*, slot*, softwarelist*, ramoption*)>
		<!ATTLIST machine name CDATA #REQUIRED>
		<!ATTLIST machine sourcefile CDATA #IMPLIED>
		<!ATTLIST machine isbios (yes|no) "no">
		<!ATTLIST machine isdevice (yes|no) "no">
		<!ATTLIST machine ismechanical (yes|no) "no">
		<!ATTLIST machine runnable (yes|no) "yes">
		<!ATTLIST machine cloneof CDATA #IMPLIED>
		<!ATTLIST machine romof CDATA #IMPLIED>
		<!ATTLIST machine sampleof CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT manufacturer (#PCDATA)>
		<!ELEMENT biosset EMPTY>
			<!ATTLIST biosset name CDATA #REQUIRED>
			<!ATTLIST biosset description CDATA #REQUIRED>
			<!ATTLIST biosset default (yes|no) "no">
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom bios CDATA #IMPLIED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom merge CDATA #IMPLIED>
			<!ATTLIST rom region CDATA #IMPLIED>
			<!ATTLIST rom offset CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good) "good">
			<!ATTLIST rom optional (yes|no) "no">
		<!ELEMENT disk EMPTY>
			<!ATTLIST disk name CDATA #REQUIRED>
			<!ATTLIST disk sha1 CDATA #IMPLIED>
			<!ATTLIST disk merge CDATA #IMPLIED>
			<!ATTLIST disk region CDATA #IMPLIED>
			<!ATTLIST disk index CDATA #IMPLIED>
			<!ATTLIST disk writable (yes|no) "no">
			<!ATTLIST disk status (baddump|nodump|good) "good">
			<!ATTLIST disk optional (yes|no) "no">
		<!ELEMENT device_ref EMPTY>
			<!ATTLIST device_ref name CDATA #REQUIRED>
		<!ELEMENT sample EMPTY>
			<!ATTLIST sample name CDATA #REQUIRED>
		<!ELEMENT chip EMPTY>
			<!ATTLIST chip name CDATA #REQUIRED>
			<!ATTLIST chip tag CDATA #IMPLIED>
			<!ATTLIST chip type (cpu|audio) #REQUIRED>
			<!ATTLIST chip clock CDATA #IMPLIED>
		<!ELEMENT display EMPTY>
			<!ATTLIST display tag CDATA #IMPLIED>
			<!ATTLIST display type (raster|vector|lcd|svg|unknown) #REQUIRED>
			<!ATTLIST display rotate (0|90|180|270) #IMPLIED>
			<!ATTLIST display flipx (yes|no) "no">
			<!ATTLIST display width CDATA #IMPLIED>
			<!ATTLIST display height CDATA #IMPLIED>
			<!ATTLIST display refresh CDATA #REQUIRED>
			<!ATTLIST display pixclock CDATA #IMPLIED>
			<!ATTLIST display htotal CDATA #IMPLIED>
			<!ATTLIST display hbend CDATA #IMPLIED>
			<!ATTLIST display hbstart CDATA #IMPLIED>
			<!ATTLIST display vtotal CDATA #IMPLIED>
			<!ATTLIST display vbend CDATA #IMPLIED>
			<!ATTLIST display vbstart CDATA #IMPLIED>
		<!ELEMENT sound EMPTY>
			<!ATTLIST sound channels CDATA #REQUIRED>
		<!ELEMENT condition EMPTY>
			<!ATTLIST condition tag CDATA #REQUIRED>
			<!ATTLIST condition mask CDATA #REQUIRED>
			<!ATTLIST condition relation (eq|ne|gt|le|lt|ge) #REQUIRED>
			<!ATTLIST condition value CDATA #REQUIRED>
		<!ELEMENT input (control*)>
			<!ATTLIST input service (yes|no) "no">
			<!ATTLIST input tilt (yes|no) "no">
			<!ATTLIST input players CDATA #REQUIRED>
			<!ATTLIST input coins CDATA #IMPLIED>
			<!ELEMENT control EMPTY>
				<!ATTLIST control type CDATA #REQUIRED>
				<!ATTLIST control player CDATA #IMPLIED>
				<!ATTLIST control buttons CDATA #IMPLIED>
				<!ATTLIST control reqbuttons CDATA #IMPLIED>
				<!ATTLIST control minimum CDATA #IMPLIED>
				<!ATTLIST control maximum CDATA #IMPLIED>
				<!ATTLIST control sensitivity CDATA #IMPLIED>
				<!ATTLIST control keydelta CDATA #IMPLIED>
				<!ATTLIST control reverse (yes|no) "no">
				<!ATTLIST control ways CDATA #IMPLIED>
				<!ATTLIST control ways2 CDATA #IMPLIED>
				<!ATTLIST control ways3 CDATA #IMPLIED>
		<!ELEMENT dipswitch (condition?, diplocation*, dipvalue*)>
			<!ATTLIST dipswitch name CDATA #REQUIRED>
			<!ATTLIST dipswitch tag CDATA #REQUIRED>
			<!ATTLIST dipswitch mask CDATA #REQUIRED>
			<!ELEMENT diplocation EMPTY>
				<!ATTLIST diplocation name CDATA #REQUIRED>
				<!ATTLIST diplocation number CDATA #REQUIRED>
				<!ATTLIST diplocation inverted (yes|no) "no">
			<!ELEMENT dipvalue (condition?)>
				<!ATTLIST dipvalue name CDATA #REQUIRED>
				<!ATTLIST dipvalue value CDATA #REQUIRED>
				<!ATTLIST dipvalue default (yes|no) "no">
		<!ELEMENT configuration (condition?, conflocation*, confsetting*)>
			<!ATTLIST configuration name CDATA #REQUIRED>
			<!ATTLIST configuration tag CDATA #REQUIRED>
			<!ATTLIST configuration mask CDATA #REQUIRED>
			<!ELEMENT conflocation EMPTY>
				<!ATTLIST conflocation name CDATA #REQUIRED>
				<!ATTLIST conflocation number CDATA #REQUIRED>
				<!ATTLIST conflocation inverted (yes|no) "no">
			<!ELEMENT confsetting (condition?)>
				<!ATTLIST confsetting name CDATA #REQUIRED>
				<!ATTLIST confsetting value CDATA #REQUIRED>
				<!ATTLIST confsetting default (yes|no) "no">
		<!ELEMENT port (analog*)>
			<!ATTLIST port tag CDATA #REQUIRED>
			<!ELEMENT analog EMPTY>
				<!ATTLIST analog mask CDATA #REQUIRED>
		<!ELEMENT adjuster (condition?)>
			<!ATTLIST adjuster name CDATA #REQUIRED>
			<!ATTLIST adjuster default CDATA #REQUIRED>
		<!ELEMENT driver EMPTY>
			<!ATTLIST driver status (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver emulation (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver cocktail (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver savestate (supported|unsupported) #REQUIRED>
			<!ATTLIST driver requiresartwork (yes|no) "no">
			<!ATTLIST driver unofficial (yes|no) "no">
			<!ATTLIST driver nosoundhardware (yes|no) "no">
			<!ATTLIST driver incomplete (yes|no) "no">
		<!ELEMENT feature EMPTY>
			<!ATTLIST feature type (protection|timing|graphics|palette|sound|capture|camera|microphone|controls|keyboard|mouse|media|disk|printer|tape|punch|drum|rom|comms|lan|wan) #REQUIRED>
			<!ATTLIST feature status (unemulated|imperfect) #IMPLIED>
			<!ATTLIST feature overall (unemulated|imperfect) #IMPLIED>
		<!ELEMENT device (instance?, extension*)>
			<!ATTLIST device type CDATA #REQUIRED>
			<!ATTLIST device tag CDATA #IMPLIED>
			<!ATTLIST device fixed_image CDATA #IMPLIED>
			<!ATTLIST device mandatory CDATA #IMPLIED>
			<!ATTLIST device interface CDATA #IMPLIED>
			<!ELEMENT instance EMPTY>
				<!ATTLIST instance name CDATA #REQUIRED>
				<!ATTLIST instance briefname CDATA #REQUIRED>
			<!ELEMENT extension EMPTY>
				<!ATTLIST extension name CDATA #REQUIRED>
		<!ELEMENT slot (slotoption*)>
			<!ATTLIST slot name CDATA #REQUIRED>
			<!ELEMENT slotoption EMPTY>
				<!ATTLIST slotoption name CDATA #REQUIRED>
				<!ATTLIST slotoption devname CDATA #REQUIRED>
				<!ATTLIST slotoption default (yes|no) "no">
		<!ELEMENT softwarelist EMPTY>
			<!ATTLIST softwarelist tag CDATA #REQUIRED>
			<!ATTLIST softwarelist name CDATA #REQUIRED>
			<!ATTLIST softwarelist status (original|compatible) #REQUIRED>
			<!ATTLIST softwarelist filter CDATA #IMPLIED>
		<!ELEMENT ramoption (#PCDATA)>
			<!ATTLIST ramoption name CDATA #REQUIRED>
			<!ATTLIST ramoption default CDATA #IMPLIED>
]>

<mame build="0.248 (unknown)" debug="no" mameconfig="10">
	<machine name="arknoid2" sourcefile="taito/tnzs.cpp">
		<description>Arkanoid - Revenge of DOH (World)</description>
		<year>1987</year>
		<manufacturer>Taito Corporation Japan</manufacturer>
		<rom name="b08__05.11c" size="65536" crc="136edf9d" sha1="f632321650897eee585511a84f451a205d1f7704" region="maincpu" offset="0"/>
		<rom name="b08__13.3e" size="65536" crc="e8035ef1" sha1="9a54e952cff0036c4b6affd9ffb1097cdccbe255" region="sub" offset="0"/>
		<rom name="b08__09.3g" size="2048" status="nodump" region="mcu" offset="0"/>
		<rom name="b08-01.13a" size="131072" crc="2ccc86b4" sha1="eced1d7e687db0331507726946b6a19a690a7604" region="gfx1" offset="0"/>
		<rom name="b08-02.10a" size="131072" crc="056a985f" sha1="6333b71c631d3307929aae633760870451830e10" region="gfx1" offset="20000"/>
		<rom name="b08-03.7a" size="131072" crc="274a795f" sha1="49353590e1a418843f57c715185e407a20021936" region="gfx1" offset="40000"/>
		<rom name="b08-04.4a" size="131072" crc="9754f703" sha1="0018ebf7da3f501345f3f5085d98d7614f8ce1b6" region="gfx1" offset="60000"/>
		<rom name="b08-08.15f" size="512" crc="a4f7ebd9" sha1="094eb63c18898c6ee8d722492bdfd28091c61773" region="proms" offset="0"/>
		<rom name="b08-07.16f" size="512" crc="ea34d9f7" sha1="9a46edc64f961bd96908419cabd92445d300fc19" region="proms" offset="200"/>
		<rom name="b06-10.pal16l8a.d9.jed" size="4096" status="nodump" region="pal" offset="0"/>
		<rom name="b06-11.pal16l8a.d6.jed" size="4096" status="nodump" region="pal" offset="1000"/>
		<rom name="b06-12.pal16l8a.c3.jed" size="4096" status="nodump" region="pal" offset="2000"/>
		<rom name="b06-13.pal16l8a.c2.jed" size="4096" status="nodump" region="pal" offset="3000"/>
		<device_ref name="z80"/>
		<device_ref name="z80"/>
		<device_ref name="address_map_bank"/>
		<device_ref name="x1_001"/>
		<device_ref name="screen"/>
		<device_ref name="palette"/>
		<device_ref name="speaker"/>
		<device_ref name="i8742"/>
		<device_ref name="ym2203"/>
		<device_ref name="upd4701a"/>
		<chip type="cpu" tag="maincpu" name="Zilog Z80" clock="6000000"/>
		<chip type="cpu" tag="sub" name="Zilog Z80" clock="6000000"/>
		<chip type="cpu" tag="mcu" name="Intel 8742" clock="6000000"/>
		<chip type="audio" tag="speaker" name="Speaker"/>
		<chip type="audio" tag="ymsnd" name="YM2203 OPN" clock="3000000"/>
		<display tag="screen" type="raster" rotate="270" width="256" height="224" refresh="60.000000" />
		<sound channels="1"/>
		<input players="2" coins="2" tilt="yes">
			<control type="dial" player="1" buttons="1" minimum="0" maximum="4095" sensitivity="70" keydelta="15"/>
			<control type="dial" player="2" buttons="1" minimum="0" maximum="4095" sensitivity="70" keydelta="15"/>
		</input>
		<dipswitch name="Cabinet" tag="DSWA" mask="1">
			<diplocation name="SWA" number="1"/>
			<dipvalue name="Upright" value="0" default="yes"/>
			<dipvalue name="Cocktail" value="1"/>
		</dipswitch>
		<dipswitch name="Flip Screen" tag="DSWA" mask="2">
			<diplocation name="SWA" number="2"/>
			<dipvalue name="Off" value="2" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Service Mode" tag="DSWA" mask="4">
			<diplocation name="SWA" number="3"/>
			<dipvalue name="Off" value="4" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Demo Sounds" tag="DSWA" mask="8">
			<diplocation name="SWA" number="4"/>
			<dipvalue name="Off" value="0"/>
			<dipvalue name="On" value="8" default="yes"/>
		</dipswitch>
		<dipswitch name="Coin A" tag="DSWA" mask="48">
			<diplocation name="SWA" number="5"/>
			<diplocation name="SWA" number="6"/>
			<dipvalue name="4 Coins/1 Credit" value="0"/>
			<dipvalue name="3 Coins/1 Credit" value="16"/>
			<dipvalue name="2 Coins/1 Credit" value="32"/>
			<dipvalue name="1 Coin/1 Credit" value="48" default="yes"/>
		</dipswitch>
		<dipswitch name="Coin B" tag="DSWA" mask="192">
			<diplocation name="SWA" number="7"/>
			<diplocation name="SWA" number="8"/>
			<dipvalue name="1 Coin/2 Credits" value="192" default="yes"/>
			<dipvalue name="1 Coin/3 Credits" value="128"/>
			<dipvalue name="1 Coin/4 Credits" value="64"/>
			<dipvalue name="1 Coin/6 Credits" value="0"/>
		</dipswitch>
		<dipswitch name="Difficulty" tag="DSWB" mask="3">
			<diplocation name="SWB" number="1"/>
			<diplocation name="SWB" number="2"/>
			<dipvalue name="Easy" value="2"/>
			<dipvalue name="Medium" value="3" default="yes"/>
			<dipvalue name="Hard" value="1"/>
			<dipvalue name="Hardest" value="0"/>
		</dipswitch>
		<dipswitch name="Bonus Life" tag="DSWB" mask="12">
			<diplocation name="SWB" number="3"/>
			<diplocation name="SWB" number="4"/>
			<dipvalue name="50k 150k 150k+" value="0"/>
			<dipvalue name="100k 200k 200k+" value="12" default="yes"/>
			<dipvalue name="50k only" value="4"/>
			<dipvalue name="100k only" value="8"/>
		</dipswitch>
		<dipswitch name="Lives" tag="DSWB" mask="48">
			<diplocation name="SWB" number="5"/>
			<diplocation name="SWB" number="6"/>
			<dipvalue name="2" value="32"/>
			<dipvalue name="3" value="48" default="yes"/>
			<dipvalue name="4" value="16"/>
			<dipvalue name="5" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="DSWB" mask="64">
			<diplocation name="SWB" number="7"/>
			<dipvalue name="Off" value="64" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Allow Continue" tag="DSWB" mask="128">
			<diplocation name="SWB" number="8"/>
			<dipvalue name="No" value="128"/>
			<dipvalue name="Yes" value="0" default="yes"/>
		</dipswitch>
		<port tag=":AN1">
			<analog mask="4095"/>
		</port>
		<port tag=":AN2">
			<analog mask="4095"/>
		</port>
		<port tag=":COIN1">
		</port>
		<port tag=":COIN2">
		</port>
		<port tag=":DSWA">
		</port>
		<port tag=":DSWB">
		</port>
		<port tag=":IN0">
		</port>
		<port tag=":IN1">
		</port>
		<port tag=":IN2">
		</port>
		<driver status="good" emulation="good" savestate="supported"/>
	</machine>
	<machine name="arknoid2b" sourcefile="taito/tnzs.cpp" cloneof="arknoid2" romof="arknoid2">
		<description>Arkanoid - Revenge of DOH (Japan bootleg)</description>
		<year>1987</year>
		<manufacturer>bootleg</manufacturer>
		<rom name="boot.11c" size="65536" crc="3847dfb0" sha1="993c8af3df7a4d5a2523f0e31a6df1c07ba13c7d" region="maincpu" offset="0"/>
		<rom name="b08_13.3e" merge="b08__13.3e" size="65536" crc="e8035ef1" sha1="9a54e952cff0036c4b6affd9ffb1097cdccbe255" region="sub" offset="0"/>
		<rom name="ark28742.3g" size="2048" status="nodump" region="mcu" offset="0"/>
		<rom name="b08-01.13a" merge="b08-01.13a" size="131072" crc="2ccc86b4" sha1="eced1d7e687db0331507726946b6a19a690a7604" region="gfx1" offset="0"/>
		<rom name="b08-02.10a" merge="b08-02.10a" size="131072" crc="056a985f" sha1="6333b71c631d3307929aae633760870451830e10" region="gfx1" offset="20000"/>
		<rom name="b08-03.7a" merge="b08-03.7a" size="131072" crc="274a795f" sha1="49353590e1a418843f57c715185e407a20021936" region="gfx1" offset="40000"/>
		<rom name="b08-04.4a" merge="b08-04.4a" size="131072" crc="9754f703" sha1="0018ebf7da3f501345f3f5085d98d7614f8ce1b6" region="gfx1" offset="60000"/>
		<rom name="b08-08.15f" merge="b08-08.15f" size="512" crc="a4f7ebd9" sha1="094eb63c18898c6ee8d722492bdfd28091c61773" region="proms" offset="0"/>
		<rom name="b08-07.16f" merge="b08-07.16f" size="512" crc="ea34d9f7" sha1="9a46edc64f961bd96908419cabd92445d300fc19" region="proms" offset="200"/>
		<rom name="b06-10.pal16l8a.d9.jed" size="4096" status="nodump" region="pal" offset="0"/>
		<rom name="b06-11.pal16l8a.d6.jed" size="4096" status="nodump" region="pal" offset="1000"/>
		<rom name="b06-12.pal16l8a.c3.jed" size="4096" status="nodump" region="pal" offset="2000"/>
		<rom name="b06-13.pal16l8a.c2.jed" size="4096" status="nodump" region="pal" offset="3000"/>
		<device_ref name="z80"/>
		<device_ref name="z80"/>
		<device_ref name="address_map_bank"/>
		<device_ref name="x1_001"/>
		<device_ref name="screen"/>
		<device_ref name="palette"/>
		<device_ref name="speaker"/>
		<device_ref name="i8742"/>
		<device_ref name="ym2203"/>
		<device_ref name="upd4701a"/>
		<chip type="cpu" tag="maincpu" name="Zilog Z80" clock="6000000"/>
		<chip type="cpu" tag="sub" name="Zilog Z80" clock="6000000"/>
		<chip type="cpu" tag="mcu" name="Intel 8742" clock="6000000"/>
		<chip type="audio" tag="speaker" name="Speaker"/>
		<chip type="audio" tag="ymsnd" name="YM2203 OPN" clock="3000000"/>
		<display tag="screen" type="raster" rotate="270" width="256" height="224" refresh="60.000000" />
		<sound channels="1"/>
		<input players="2" coins="2" tilt="yes">
			<control type="dial" player="1" buttons="1" minimum="0" maximum="4095" sensitivity="70" keydelta="15"/>
			<control type="dial" player="2" buttons="1" minimum="0" maximum="4095" sensitivity="70" keydelta="15"/>
		</input>
		<dipswitch name="Cabinet" tag="DSWA" mask="1">
			<diplocation name="SWA" number="1"/>
			<dipvalue name="Upright" value="0" default="yes"/>
			<dipvalue name="Cocktail" value="1"/>
		</dipswitch>
		<dipswitch name="Flip Screen" tag="DSWA" mask="2">
			<diplocation name="SWA" number="2"/>
			<dipvalue name="Off" value="2" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Service Mode" tag="DSWA" mask="4">
			<diplocation name="SWA" number="3"/>
			<dipvalue name="Off" value="4" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Demo Sounds" tag="DSWA" mask="8">
			<diplocation name="SWA" number="4"/>
			<dipvalue name="Off" value="0"/>
			<dipvalue name="On" value="8" default="yes"/>
		</dipswitch>
		<dipswitch name="Coin A" tag="DSWA" mask="48">
			<diplocation name="SWA" number="5"/>
			<diplocation name="SWA" number="6"/>
			<dipvalue name="2 Coins/1 Credit" value="16"/>
			<dipvalue name="1 Coin/1 Credit" value="48" default="yes"/>
			<dipvalue name="2 Coins/3 Credits" value="0"/>
			<dipvalue name="1 Coin/2 Credits" value="32"/>
		</dipswitch>
		<dipswitch name="Coin B" tag="DSWA" mask="192">
			<diplocation name="SWA" number="7"/>
			<diplocation name="SWA" number="8"/>
			<dipvalue name="2 Coins/1 Credit" value="64"/>
			<dipvalue name="1 Coin/1 Credit" value="192" default="yes"/>
			<dipvalue name="2 Coins/3 Credits" value="0"/>
			<dipvalue name="1 Coin/2 Credits" value="128"/>
		</dipswitch>
		<dipswitch name="Difficulty" tag="DSWB" mask="3">
			<diplocation name="SWB" number="1"/>
			<diplocation name="SWB" number="2"/>
			<dipvalue name="Easy" value="2"/>
			<dipvalue name="Medium" value="3" default="yes"/>
			<dipvalue name="Hard" value="1"/>
			<dipvalue name="Hardest" value="0"/>
		</dipswitch>
		<dipswitch name="Bonus Life" tag="DSWB" mask="12">
			<diplocation name="SWB" number="3"/>
			<diplocation name="SWB" number="4"/>
			<dipvalue name="50k 150k 150k+" value="0"/>
			<dipvalue name="100k 200k 200k+" value="12" default="yes"/>
			<dipvalue name="50k only" value="4"/>
			<dipvalue name="100k only" value="8"/>
		</dipswitch>
		<dipswitch name="Lives" tag="DSWB" mask="48">
			<diplocation name="SWB" number="5"/>
			<diplocation name="SWB" number="6"/>
			<dipvalue name="2" value="32"/>
			<dipvalue name="3" value="48" default="yes"/>
			<dipvalue name="4" value="16"/>
			<dipvalue name="5" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="DSWB" mask="64">
			<diplocation name="SWB" number="7"/>
			<dipvalue name="Off" value="64" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Allow Continue" tag="DSWB" mask="128">
			<diplocation name="SWB" number="8"/>
			<dipvalue name="No" value="128"/>
			<dipvalue name="Yes" value="0" default="yes"/>
		</dipswitch>
		<port tag=":AN1">
			<analog mask="4095"/>
		</port>
		<port tag=":AN2">
			<analog mask="4095"/>
		</port>
		<port tag=":COIN1">
		</port>
		<port tag=":COIN2">
		</port>
		<port tag=":DSWA">
		</port>
		<port tag=":DSWB">
		</port>
		<port tag=":IN0">
		</port>
		<port tag=":IN1">
		</port>
		<port tag=":IN2">
		</port>
		<driver status="good" emulation="good" savestate="supported"/>
	</machine>
	<machine name="arknoid2j" sourcefile="taito/tnzs.cpp" cloneof="arknoid2" romof="arknoid2">
		<description>Arkanoid - Revenge of DOH (Japan)</description>
		<year>1987</year>
		<manufacturer>Taito Corporation</manufacturer>
		<rom name="b08_05.11c" merge="b08__05.11c" size="65536" crc="136edf9d" sha1="f632321650897eee585511a84f451a205d1f7704" region="maincpu" offset="0"/>
		<rom name="b08_06.3e" size="65536" crc="adfcd40c" sha1="f91299407ed21e2dd244c9b1a315b27ed32f5514" region="sub" offset="0"/>
		<rom name="b08__09.3g" size="2048" status="nodump" region="mcu" offset="0"/>
		<rom name="b08-01.13a" merge="b08-01.13a" size="131072" crc="2ccc86b4" sha1="eced1d7e687db0331507726946b6a19a690a7604" region="gfx1" offset="0"/>
		<rom name="b08-02.10a" merge="b08-02.10a" size="131072" crc="056a985f" sha1="6333b71c631d3307929aae633760870451830e10" region="gfx1" offset="20000"/>
		<rom name="b08-03.7a" merge="b08-03.7a" size="131072" crc="274a795f" sha1="49353590e1a418843f57c715185e407a20021936" region="gfx1" offset="40000"/>
		<rom name="b08-04.4a" merge="b08-04.4a" size="131072" crc="9754f703" sha1="0018ebf7da3f501345f3f5085d98d7614f8ce1b6" region="gfx1" offset="60000"/>
		<rom name="b08-08.15f" merge="b08-08.15f" size="512" crc="a4f7ebd9" sha1="094eb63c18898c6ee8d722492bdfd28091c61773" region="proms" offset="0"/>
		<rom name="b08-07.16f" merge="b08-07.16f" size="512" crc="ea34d9f7" sha1="9a46edc64f961bd96908419cabd92445d300fc19" region="proms" offset="200"/>
		<rom name="b06-10.pal16l8a.d9.jed" size="4096" status="nodump" region="pal" offset="0"/>
		<rom name="b06-11.pal16l8a.d6.jed" size="4096" status="nodump" region="pal" offset="1000"/>
		<rom name="b06-12.pal16l8a.c3.jed" size="4096" status="nodump" region="pal" offset="2000"/>
		<rom name="b06-13.pal16l8a.c2.jed" size="4096" status="nodump" region="pal" offset="3000"/>
		<device_ref name="z80"/>
		<device_ref name="z80"/>
		<device_ref name="address_map_bank"/>
		<device_ref name="x1_001"/>
		<device_ref name="screen"/>
		<device_ref name="palette"/>
		<device_ref name="speaker"/>
		<device_ref name="i8742"/>
		<device_ref name="ym2203"/>
		<device_ref name="upd4701a"/>
		<chip type="cpu" tag="maincpu" name="Zilog Z80" clock="6000000"/>
		<chip type="cpu" tag="sub" name="Zilog Z80" clock="6000000"/>
		<chip type="cpu" tag="mcu" name="Intel 8742" clock="6000000"/>
		<chip type="audio" tag="speaker" name="Speaker"/>
		<chip type="audio" tag="ymsnd" name="YM2203 OPN" clock="3000000"/>
		<display tag="screen" type="raster" rotate="270" width="256" height="224" refresh="60.000000" />
		<sound channels="1"/>
		<input players="2" coins="2" tilt="yes">
			<control type="dial" player="1" buttons="1" minimum="0" maximum="4095" sensitivity="70" keydelta="15"/>
			<control type="dial" player="2" buttons="1" minimum="0" maximum="4095" sensitivity="70" keydelta="15"/>
		</input>
		<dipswitch name="Cabinet" tag="DSWA" mask="1">
			<diplocation name="SWA" number="1"/>
			<dipvalue name="Upright" value="0" default="yes"/>
			<dipvalue name="Cocktail" value="1"/>
		</dipswitch>
		<dipswitch name="Flip Screen" tag="DSWA" mask="2">
			<diplocation name="SWA" number="2"/>
			<dipvalue name="Off" value="2" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Service Mode" tag="DSWA" mask="4">
			<diplocation name="SWA" number="3"/>
			<dipvalue name="Off" value="4" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Demo Sounds" tag="DSWA" mask="8">
			<diplocation name="SWA" number="4"/>
			<dipvalue name="Off" value="0"/>
			<dipvalue name="On" value="8" default="yes"/>
		</dipswitch>
		<dipswitch name="Coin A" tag="DSWA" mask="48">
			<diplocation name="SWA" number="5"/>
			<diplocation name="SWA" number="6"/>
			<dipvalue name="2 Coins/1 Credit" value="16"/>
			<dipvalue name="1 Coin/1 Credit" value="48" default="yes"/>
			<dipvalue name="2 Coins/3 Credits" value="0"/>
			<dipvalue name="1 Coin/2 Credits" value="32"/>
		</dipswitch>
		<dipswitch name="Coin B" tag="DSWA" mask="192">
			<diplocation name="SWA" number="7"/>
			<diplocation name="SWA" number="8"/>
			<dipvalue name="2 Coins/1 Credit" value="64"/>
			<dipvalue name="1 Coin/1 Credit" value="192" default="yes"/>
			<dipvalue name="2 Coins/3 Credits" value="0"/>
			<dipvalue name="1 Coin/2 Credits" value="128"/>
		</dipswitch>
		<dipswitch name="Difficulty" tag="DSWB" mask="3">
			<diplocation name="SWB" number="1"/>
			<diplocation name="SWB" number="2"/>
			<dipvalue name="Easy" value="2"/>
			<dipvalue name="Medium" value="3" default="yes"/>
			<dipvalue name="Hard" value="1"/>
			<dipvalue name="Hardest" value="0"/>
		</dipswitch>
		<dipswitch name="Bonus Life" tag="DSWB" mask="12">
			<diplocation name="SWB" number="3"/>
			<diplocation name="SWB" number="4"/>
			<dipvalue name="50k 150k 150k+" value="0"/>
			<dipvalue name="100k 200k 200k+" value="12" default="yes"/>
			<dipvalue name="50k only" value="4"/>
			<dipvalue name="100k only" value="8"/>
		</dipswitch>
		<dipswitch name="Lives" tag="DSWB" mask="48">
			<diplocation name="SWB" number="5"/>
			<diplocation name="SWB" number="6"/>
			<dipvalue name="2" value="32"/>
			<dipvalue name="3" value="48" default="yes"/>
			<dipvalue name="4" value="16"/>
			<dipvalue name="5" value="0"/>
		</dipswitch>
		<dipswitch name="Unused" tag="DSWB" mask="64">
			<diplocation name="SWB" number="7"/>
			<dipvalue name="Off" value="64" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Allow Continue" tag="DSWB" mask="128">
			<diplocation name="SWB" number="8"/>
			<dipvalue name="No" value="128"/>
			<dipvalue name="Yes" value="0" default="yes"/>
		</dipswitch>
		<port tag=":AN1">
			<analog mask="4095"/>
		</port>
		<port tag=":AN2">
			<analog mask="4095"/>
		</port>
		<port tag=":COIN1">
		</port>
		<port tag=":COIN2">
		</port>
		<port tag=":DSWA">
		</port>
		<port tag=":DSWB">
		</port>
		<port tag=":IN0">
		</port>
		<port tag=":IN1">
		</port>
		<port tag=":IN2">
		</port>
		<driver status="good" emulation="good" savestate="supported"/>
	</machine>
	<machine name="arknoid2u" sourcefile="taito/tnzs.cpp" cloneof="arknoid2" romof="arknoid2">
		<description>Arkanoid - Revenge of DOH (US)</description>
		<year>1987</year>
		<manufacturer>Taito America Corporation (Romstar license)</manufacturer>
		<rom name="b08__11.11c" size="65536" crc="99555231" sha1="2798f3f5b3f1fa27598fe7a6e95c75d9142c8d34" region="maincpu" offset="0"/>
		<rom name="b08__12.3e" size="65536" crc="dc84e27d" sha1="d549d8c9fbec0521517f0c5f5cee763e27d48633" region="sub" offset="0"/>
		<rom name="b08__09.3g" size="2048" status="nodump" region="mcu" offset="0"/>
		<rom name="b08-01.13a" merge="b08-01.13a" size="131072" crc="2ccc86b4" sha1="eced1d7e687db0331507726946b6a19a690a7604" region="gfx1" offset="0"/>
		<rom name="b08-02.10a" merge="b08-02.10a" size="131072" crc="056a985f" sha1="6333b71c631d3307929aae633760870451830e10" region="gfx1" offset="20000"/>
		<rom name="b08-03.7a" merge="b08-03.7a" size="131072" crc="274a795f" sha1="49353590e1a418843f57c715185e407a20021936" region="gfx1" offset="40000"/>
		<rom name="b08-04.4a" merge="b08-04.4a" size="131072" crc="9754f703" sha1="0018ebf7da3f501345f3f5085d98d7614f8ce1b6" region="gfx1" offset="60000"/>
		<rom name="b08-08.15f" merge="b08-08.15f" size="512" crc="a4f7ebd9" sha1="094eb63c18898c6ee8d722492bdfd28091c61773" region="proms" offset="0"/>
		<rom name="b08-07.16f" merge="b08-07.16f" size="512" crc="ea34d9f7" sha1="9a46edc64f961bd96908419cabd92445d300fc19" region="proms" offset="200"/>
		<rom name="b06-10.pal16l8a.d9.jed" size="4096" status="nodump" region="pal" offset="0"/>
		<rom name="b06-11.pal16l8a.d6.jed" size="4096" status="nodump" region="pal" offset="1000"/>
		<rom name="b06-12.pal16l8a.c3.jed" size="4096" status="nodump" region="pal" offset="2000"/>
		<rom name="b06-13.pal16l8a.c2.jed" size="4096" status="nodump" region="pal" offset="3000"/>
		<device_ref name="z80"/>
		<device_ref name="z80"/>
		<device_ref name="address_map_bank"/>
		<device_ref name="x1_001"/>
		<device_ref name="screen"/>
		<device_ref name="palette"/>
		<device_ref name="speaker"/>
		<device_ref name="i8742"/>
		<device_ref name="ym2203"/>
		<device_ref name="upd4701a"/>
		<chip type="cpu" tag="maincpu" name="Zilog Z80" clock="6000000"/>
		<chip type="cpu" tag="sub" name="Zilog Z80" clock="6000000"/>
		<chip type="cpu" tag="mcu" name="Intel 8742" clock="6000000"/>
		<chip type="audio" tag="speaker" name="Speaker"/>
		<chip type="audio" tag="ymsnd" name="YM2203 OPN" clock="3000000"/>
		<display tag="screen" type="raster" rotate="270" width="256" height="224" refresh="60.000000" />
		<sound channels="1"/>
		<input players="2" coins="2" tilt="yes">
			<control type="dial" player="1" buttons="1" minimum="0" maximum="4095" sensitivity="70" keydelta="15"/>
			<control type="dial" player="2" buttons="1" minimum="0" maximum="4095" sensitivity="70" keydelta="15"/>
		</input>
		<dipswitch name="Cabinet" tag="DSWA" mask="1">
			<diplocation name="SWA" number="1"/>
			<dipvalue name="Upright" value="0" default="yes"/>
			<dipvalue name="Cocktail" value="1"/>
		</dipswitch>
		<dipswitch name="Flip Screen" tag="DSWA" mask="2">
			<diplocation name="SWA" number="2"/>
			<dipvalue name="Off" value="2" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Service Mode" tag="DSWA" mask="4">
			<diplocation name="SWA" number="3"/>
			<dipvalue name="Off" value="4" default="yes"/>
			<dipvalue name="On" value="0"/>
		</dipswitch>
		<dipswitch name="Demo Sounds" tag="DSWA" mask="8">
			<diplocation name="SWA" number="4"/>
			<dipvalue name="Off" value="0"/>
			<dipvalue name="On" value="8" default="yes"/>
		</dipswitch>
		<dipswitch name="Coin A" tag="DSWA" mask="48">
			<diplocation name="SWA" number="5"/>
			<diplocation name="SWA" number="6"/>
			<dipvalue name="2 Coins/1 Credit" value="16"/>
			<dipvalue name="1 Coin/1 Credit" value="48" default="yes"/>
			<dipvalue name="2 Coins/3 Credits" value="0"/>
			<dipvalue name="1 Coin/2 Credits" value="32"/>
		</dipswitch>
		<dipswitch name="Coin B" tag="DSWA" mask="192">
			<diplocation name="SWA" number="7"/>
			<diplocation name="SWA" number="8"/>
			<dipvalue name="2 Coins/1 Credit" value="64"/>
			<dipvalue name="1 Coin/1 Credit" value="192" default="yes"/>
			<dipvalue name="2 Coins/3 Credits" value="0"/>
			<dipvalue name="1 Coin/2 Credits" value="128"/>
		</dipswitch>
		<dipswitch name="Difficulty" tag="DSWB" mask="3">
			<diplocation name="SWB" number="1"/>
			<diplocation name="SWB" number="2"/>
			<dipvalue name="Easy" value="2"/>